-- MySQL Script generated by MySQL Workbench
-- Fri Oct  9 10:29:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_inventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_inventario` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `db_inventario` ;

-- -----------------------------------------------------
-- Table `db_inventario`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`categorias` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(300) NULL,
  `condicion` VARCHAR(45) NULL,
  `categoriacol` TINYINT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inventario`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`productos` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `idcategoria` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `stock` INT NOT NULL,
  `descripcion` VARCHAR(300) NULL,
  `imagen` VARCHAR(45) NULL,
  `estado_bodega` VARCHAR(20) NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_productos_categorias_idx` (`idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_productos_categorias`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `db_inventario`.`categorias` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inventario`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo_documento` VARCHAR(45) NULL,
  `no_documento` VARCHAR(20) NULL,
  `direccion` VARCHAR(70) NULL,
  `telefono` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inventario`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`inventario` (
  `idinventario` INT NOT NULL AUTO_INCREMENT,
  `idproveedor` INT NOT NULL,
  `no_comprobante` VARCHAR(45) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  PRIMARY KEY (`idinventario`),
  INDEX `fk_inventario_persona_idx` (`idproveedor` ASC) VISIBLE,
  CONSTRAINT `fk_inventario_persona`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `db_inventario`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inventario`.`mov_inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`mov_inventario` (
  `idmov_inventario` INT NOT NULL AUTO_INCREMENT,
  `idinventario` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idmov_inventario`),
  INDEX `fk_mov_inventario_idx` (`idinventario` ASC) VISIBLE,
  INDEX `fk_mov_productos_idx` (`idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_mov_inventario`
    FOREIGN KEY (`idinventario`)
    REFERENCES `db_inventario`.`inventario` (`idinventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mov_productos`
    FOREIGN KEY (`idproducto`)
    REFERENCES `db_inventario`.`productos` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inventario`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `tipo_documento` VARCHAR(45) NOT NULL,
  `no_documento` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inventario`.`solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`solicitudes` (
  `idsolicitud` INT NOT NULL AUTO_INCREMENT,
  `idtaller` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `no_comprobante` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `usuarios_idusuario` INT NOT NULL,
  PRIMARY KEY (`idsolicitud`),
  INDEX `fk_solicitud_taller_idx` (`idtaller` ASC) VISIBLE,
  INDEX `fk_solicitudes_usuarios1_idx` (`usuarios_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_solicitud_taller`
    FOREIGN KEY (`idtaller`)
    REFERENCES `db_inventario`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitudes_usuarios1`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `db_inventario`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inventario`.`mov_solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`mov_solicitudes` (
  `idmov_solicitudes` INT NOT NULL AUTO_INCREMENT,
  `idsolicitud` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idmov_solicitudes`),
  INDEX `fk_mov_solicitud_idx` (`idsolicitud` ASC) VISIBLE,
  INDEX `fk_mov_producto_idx` (`idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_mov_solicitud`
    FOREIGN KEY (`idsolicitud`)
    REFERENCES `db_inventario`.`solicitudes` (`idsolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mov_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `db_inventario`.`productos` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inventario`.`bodegas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`bodegas` (
  `idbodega` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idbodega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inventario`.`almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`almacen` (
  `idalmacen` INT NOT NULL AUTO_INCREMENT,
  `idbodega` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idalmacen`),
  INDEX `fk_almacen_bodega_idx` (`idbodega` ASC) VISIBLE,
  INDEX `fk_almacen_productos_idx` (`idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_almacen_bodega`
    FOREIGN KEY (`idbodega`)
    REFERENCES `db_inventario`.`bodegas` (`idbodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_almacen_productos`
    FOREIGN KEY (`idproducto`)
    REFERENCES `db_inventario`.`productos` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
